[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = [
    'python -m venv --copies venv',
    '. venv/bin/activate && pip install --upgrade pip setuptools wheel',
    '. venv/bin/activate && pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase completed"']

[start]
cmd = '. venv/bin/activate && gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 180 --preload --access-logfile - --error-logfile - wsgi:application'
